name: Docker Build and Test

on:
  workflow_dispatch:

jobs:
  docker-build-test:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout repository
        uses: actions/checkout@v4

      - name: Set up Docker Buildx
        uses: docker/setup-buildx-action@v3

      - name: Build Docker image
        uses: docker/build-push-action@v6
        with:
          context: .
          file: ./Dockerfile
          push: false
          tags: fizzbuzz-app:latest

      - name: Run tests in Docker container
        run: docker run --rm fizzbuzz-app python -m unittest discover
